"""
DEEP — Wireshark Lua Dissector Generator
Generates .lua dissector files from InferredProtocol analysis.
Drop the generated file into your Wireshark plugins directory.
"""
from __future__ import annotations

from typing import Optional
from .binary_protocol import InferredProtocol


class DissectorGenerator:
    """
    Generate Wireshark Lua dissectors from InferredProtocol objects.
    """

    def generate(
        self,
        proto: InferredProtocol,
        protocol_name: str,
        port: int,
        transport: str = "tcp",
        output_path: Optional[str] = None,
    ) -> str:
        """
        Generate a Lua dissector for Wireshark.
        protocol_name: short name (used as dissector name)
        port:          port number to register on
        transport:     "tcp" | "udp"
        Returns: Lua code as a string
        """
        pname = protocol_name.replace(" ", "_").replace("-", "_").lower()
        fname = protocol_name.upper()

        lines = [
            f'-- DEEP Auto-Generated Wireshark Dissector',
            f'-- Protocol: {fname}',
            f'-- Port: {port}/{transport.upper()}',
            f'-- Generated by DEEP ETIS Protocol Reverse Engineer',
            f'-- Entropy: {proto.entropy_bits_per_byte:.2f} bits/byte',
            f'-- Confidence: {proto.confidence:.0%}',
            f'',
            f'local {pname}_proto = Proto("{pname}", "{fname}")',
            f'',
            f'-- Field definitions',
        ]

        # Add field definitions
        field_vars = []
        for i, field in enumerate(proto.fields):
            var = f"f_{pname}_{field.field_type}_{i}"
            field_vars.append((var, field))
            label = f"{field.field_type.replace('_', ' ').title()} (offset {field.offset})"
            
            if field.size == 1:
                ftype = "uint8"
            elif field.size == 2:
                ftype = "uint16"
            elif field.size == 4:
                ftype = "uint32"
            else:
                ftype = "bytes"

            base = "HEX" if field.field_type in ("magic", "checksum", "command") else "DEC"
            
            if ftype == "bytes":
                lines.append(f'local {var} = ProtoField.bytes("{pname}.{field.field_type}_{i}", "{label}")')
            else:
                lines.append(f'local {var} = ProtoField.{ftype}("{pname}.{field.field_type}_{i}", "{label}", base.{base})')

        lines += [
            f'',
            f'{pname}_proto.fields = {{',
        ]
        for var, _ in field_vars:
            lines.append(f'    {var},')
        lines.append(f'}}')

        lines += [
            f'',
            f'-- Dissector function',
            f'function {pname}_proto.dissector(buffer, pinfo, tree)',
            f'    local length = buffer:len()',
            f'    if length == 0 then return end',
            f'',
            f'    pinfo.cols.protocol = "{fname}"',
            f'    local subtree = tree:add({pname}_proto, buffer(), "{fname} Protocol")',
            f'',
        ]

        for var, field in field_vars:
            offset = field.offset
            size = field.size
            if offset + size > 0:
                lines.append(
                    f'    if length >= {offset + size} then'
                )
                if field.field_type == "magic":
                    lines.append(f'        subtree:add({var}, buffer({offset}, {size}))')
                    if field.example_values:
                        magic_hex = field.example_values[0].replace("0x", "").replace(" ", "")
                        lines.append(f'        -- Expected magic: 0x{magic_hex}')
                elif field.field_type == "length":
                    lines.append(f'        local plen = buffer({offset}, {size}):uint()')
                    lines.append(f'        subtree:add({var}, buffer({offset}, {size})):append_text(" (payload length)")')
                elif field.field_type == "sequence":
                    lines.append(f'        local seq = buffer({offset}, {size}):uint()')
                    lines.append(f'        subtree:add({var}, buffer({offset}, {size})):append_text(string.format(" (seq #%d)", seq))')
                elif field.field_type == "command":
                    lines.append(f'        local cmd = buffer({offset}, {size}):uint()')
                    lines.append(f'        subtree:add({var}, buffer({offset}, {size})):append_text(string.format(" (cmd=0x%02X)", cmd))')
                else:
                    lines.append(f'        subtree:add({var}, buffer({offset}, {size}))')
                lines.append(f'    end')
                lines.append(f'')

        lines += [
            f'end',
            f'',
            f'-- Register on {transport.upper()} port {port}',
            f'local {transport}_table = DissectorTable.get("{transport}.port")',
            f'{transport}_table:add({port}, {pname}_proto)',
            f'',
            f'-- To install: copy this file to:',
            f'--   Windows: %APPDATA%\\Wireshark\\plugins\\',
            f'--   Linux:   ~/.config/wireshark/plugins/',
            f'--   macOS:   ~/Library/Application Support/Wireshark/plugins/',
            f'print("[DEEP] {fname} dissector loaded on {transport.upper()} port {port}")',
        ]

        lua_code = "\n".join(lines)

        if output_path:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(lua_code)

        return lua_code
